<?php
require_once 'config/conexao.php';

$entities = [
  'pizzas' => ['title'=>'Pizzas','singular'=>'pizza','fields'=>['categoria_id'=>'Categoria','nome'=>'Nome','descricao'=>'Descrição','preco'=>'Preço','badge'=>'Selo','imagem'=>'Imagem']],
  'categorias' => ['title'=>'Categorias','singular'=>'categoria','fields'=>['nome'=>'Nome','descricao'=>'Descrição']],
  'depoimentos' => ['title'=>'Depoimentos','singular'=>'depoimento','fields'=>['nome'=>'Cliente','texto'=>'Depoimento','nota'=>'Nota (1 a 5)']]
];
$entity = $entity ?? ($_GET['entity'] ?? 'pizzas');
if (!isset($entities[$entity])) { http_response_code(404); exit('Cadastro não encontrado.'); }
$meta = $entities[$entity]; $action = $_GET['action'] ?? 'list'; $id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT);
$images = ['images/pizza-margherita.png'=>'Margherita','images/pizza-pepperoni.png'=>'Pepperoni','images/pizza-quatro-queijos.png'=>'Quatro queijos','images/pizza-portuguesa.png'=>'Portuguesa','images/pizza-especial.png'=>'Especial da casa','images/pizza-calzone.png'=>'Calzone'];
$categories = $pdo->query('SELECT id,nome FROM categorias ORDER BY nome')->fetchAll();
function url($entity,$action='list',$id=null){$q='crud.php?entity='.urlencode($entity).'&action='.urlencode($action);return $id?$q.'&id='.(int)$id:$q;}
function e($value){return htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');}
$error=''; $item=[];
if ($action === 'delete' && !$id) { header('Location: '.url($entity)); exit; }
if ($action === 'delete') { $stmt=$pdo->prepare("SELECT * FROM $entity WHERE id=?");$stmt->execute([$id]);$item=$stmt->fetch();if(!$item){header('Location: '.url($entity));exit;} if($_SERVER['REQUEST_METHOD']==='POST'){ $pdo->prepare("DELETE FROM $entity WHERE id=?")->execute([$id]); header('Location: '.url($entity,'list').'&msg=excluido'); exit; } }
if (in_array($action,['create','edit'],true)) {
  if($action==='edit'){if(!$id){header('Location: '.url($entity));exit;}$stmt=$pdo->prepare("SELECT * FROM $entity WHERE id=?");$stmt->execute([$id]);$item=$stmt->fetch();if(!$item){header('Location: '.url($entity));exit;}}
  if($_SERVER['REQUEST_METHOD']==='POST'){
    foreach(array_keys($meta['fields']) as $field){$item[$field]=trim($_POST[$field]??'');}
    if($entity==='pizzas'){ $item['categoria_id']=$item['categoria_id']!==''?(int)$item['categoria_id']:null; $item['preco']=str_replace(',','.', $item['preco']); if($item['nome']===''||$item['descricao']===''||!is_numeric($item['preco'])||$item['preco']<0||$item['imagem']==='')$error='Preencha nome, descrição, preço válido e imagem.'; }
    if($entity==='categorias' && $item['nome']==='')$error='Informe o nome da categoria.';
    if($entity==='depoimentos' && ($item['nome']===''||$item['texto']===''||!filter_var($item['nota'],FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>5]])))$error='Informe cliente, depoimento e uma nota entre 1 e 5.';
    if($error===''){ $fields=array_keys($meta['fields']); if($action==='create'){ $sql="INSERT INTO $entity (".implode(',',$fields).") VALUES (".implode(',',array_fill(0,count($fields),'?')).")";$pdo->prepare($sql)->execute(array_values($item)); } else { $sql="UPDATE $entity SET ".implode(',',array_map(fn($f)=>"$f=?",$fields))." WHERE id=?";$values=array_values($item);$values[]=$id;$pdo->prepare($sql)->execute($values); } header('Location: '.url($entity,'list').'&msg='.($action==='create'?'criado':'atualizado'));exit; }
  }
}
if($action==='list'){$sql=$entity==='pizzas'?'SELECT pizzas.*,categorias.nome AS categoria_nome FROM pizzas LEFT JOIN categorias ON categorias.id=pizzas.categoria_id ORDER BY pizzas.id DESC':"SELECT * FROM $entity ORDER BY id DESC";$items=$pdo->query($sql)->fetchAll();}
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($meta['title'])?> — Administração Magleoni</title><link rel="stylesheet" href="admin.css"></head><body><header class="admin-bar"><a class="admin-brand" href="index.php">MAGLEONI <small>ADMINISTRAÇÃO</small></a><nav class="admin-nav"><a href="crud.php?entity=pizzas">Pizzas</a><a href="crud.php?entity=categorias">Categorias</a><a href="crud.php?entity=depoimentos">Depoimentos</a><a href="index.php">Ver site ↗</a></nav></header><main class="admin-main">
<?php if($action==='list'): ?><section class="admin-head"><div><p class="admin-kicker">CRUD completo</p><h1><?=e($meta['title'])?></h1><p>Cadastre, consulte, edite e exclua <?=e(strtolower($meta['title']))?>.</p></div><div class="admin-actions"><a class="button-admin button-outline" href="index.php">Voltar ao site</a><a class="button-admin" href="<?=e(url($entity,'create'))?>">+ Nova <?=e($meta['singular'])?></a></div></section><?php if(isset($_GET['msg'])):?><div class="notice">Registro <?=e($_GET['msg'])?> com sucesso.</div><?php endif;?><div class="admin-table-wrap"><table class="admin-table"><thead><tr><?php if($entity==='pizzas'):?><th>Imagem</th><?php endif;?><th>ID</th><?php foreach($meta['fields'] as $field=>$label):if(!in_array($field,['descricao','imagem','texto','categoria_id'],true)):?><th><?=e($label)?></th><?php endif;endforeach;?><th>Ações</th></tr></thead><tbody><?php foreach($items as $row):?><tr><?php if($entity==='pizzas'):?><td><img class="admin-thumb" src="<?=e($row['imagem'])?>" alt=""></td><?php endif;?><td>#<?=e($row['id'])?></td><?php if($entity==='pizzas'):?><td><?=e($row['nome'])?></td><td><?=e($row['preco'])?></td><td><?=e($row['badge']?:'—')?></td><?php elseif($entity==='categorias'):?><td><?=e($row['nome'])?></td><?php else:?><td><?=e($row['nome'])?></td><td><?=str_repeat('★',(int)$row['nota'])?></td><?php endif;?><td><a href="<?=e(url($entity,'edit',$row['id']))?>">Editar</a><a href="<?=e(url($entity,'delete',$row['id']))?>">Excluir</a></td></tr><?php endforeach;?><?php if(empty($items)):?><tr><td colspan="6">Ainda não há registros.</td></tr><?php endif;?></tbody></table></div>
<?php else: ?><section class="admin-head"><div><p class="admin-kicker">CRUD completo</p><h1><?= $action==='delete'?'Excluir':' '.($action==='create'?'Nova ':'Editar ').e($meta['singular']) ?></h1><p><?= $action==='delete'?'Esta ação precisa de confirmação.':'Preencha os dados abaixo.' ?></p></div><a class="button-admin button-outline" href="<?=e(url($entity))?>">Voltar</a></section><?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif;?><?php if($action==='delete'):?><form class="admin-form" method="post"><p>Tem certeza que deseja excluir <strong><?=e($item['nome'])?></strong>?</p><div class="form-footer"><a class="button-admin button-outline" href="<?=e(url($entity))?>">Cancelar</a><button class="button-admin button-danger">Excluir permanentemente</button></div></form><?php else:?><form class="admin-form" method="post"><?php foreach($meta['fields'] as $field=>$label):?><div class="field"><label for="<?=$field?>"><?=e($label)?></label><?php if($field==='descricao'||$field==='texto'):?><textarea id="<?=$field?>" name="<?=$field?>" required><?=e($item[$field]??'')?></textarea><?php elseif($field==='categoria_id'):?><select id="categoria_id" name="categoria_id"><option value="">Sem categoria</option><?php foreach($categories as $category):?><option value="<?=e($category['id'])?>" <?=($item[$field]??'')==$category['id']?'selected':''?>><?=e($category['nome'])?></option><?php endforeach;?></select><?php elseif($field==='imagem'):?><select id="imagem" name="imagem" required><?php foreach($images as $path=>$name):?><option value="<?=e($path)?>" <?=($item[$field]??'')===$path?'selected':''?>><?=e($name)?></option><?php endforeach;?></select><?php else:?><input id="<?=$field?>" name="<?=$field?>" value="<?=e($item[$field]??'')?>" <?= $field==='preco'?'type="number" min="0" step="0.01"':'type="'.($field==='nota'?'number':'text').'"'.($field==='nota'?' min="1" max="5"':'')?> required><?php endif;?></div><?php endforeach;?><div class="form-footer"><a class="button-admin button-outline" href="<?=e(url($entity))?>">Cancelar</a><button class="button-admin">Salvar <?=e($meta['singular'])?></button></div></form><?php endif;?><?php endif;?></main><footer class="admin-footer">Papa's Magleoni · Painel administrativo escolar</footer></body></html>
